import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"],  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="flex min-h-screen flex-col items-center justify-center"
    >
      <body className=" min-w-[600px] max-w-[600px]">
        <div className=" bg-mainOffset p-6 rounded-lg ">{children}</div>
      </body>
    </html>
  );
}
